FROM node:8.16.0

RUN set -x && \
  apt-get update -y -qq && \
  apt-get install -y -qq git

RUN git clone https://github.com/OpenVSLAM-Community/openvslam.git /openvslam
WORKDIR /openvslam/
RUN set -x && \
  cd ./viewer/ && \
  npm install

ENTRYPOINT ["node", "/openvslam/viewer/app.js"]
