version: '3'
services:
  openvslam-cpu:
    network_mode: host
    build: 
      context: .
      dockerfile: Dockerfile.cpu
      args:
        NUM_THREADS: 7
    container_name: 'openvslam-cpu'
    volumes: 
    - ./:/opt/app
    - /opt/app/node_modules/
  openvslam-nvidia:
    network_mode: host
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile.nvidia
      args:
        NUM_THREADS: 7
    container_name: 'openvslam-nvidia'
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes: 
    - ./:/opt/app
    - /opt/app/node_modules/