version: '3'
services:
  openvslam-cpu:
    network_mode: host
    image: openhps/openvslam-nodejs:ubuntu18.04-openvslam0.3.2-node14-opencv4.5.5-cpu
    container_name: 'openvslam-cpu'
    entrypoint: /opt/app/docker/docker-entrypoint.sh
    volumes: 
    - ./:/opt/app
    - /opt/app/node_modules/
  openvslam-cuda:
    network_mode: host
    image: openhps/openvslam-nodejs:ubuntu18.04-openvslam0.3.2-node14-opencv4.5.5-cuda
    container_name: 'openvslam-cuda'
    entrypoint: /opt/app/docker/docker-entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes: 
    - ./:/opt/app
    - /opt/app/node_modules/