FROM node:8.16.0-alpine

RUN apk add git

RUN git clone https://github.com/stella-cv/stella_vslam.git /tmp/stella_vslam && \
    cp -r -a /tmp/stella_vslam/viewer /viewer

RUN set -x && \
  cd /viewer/ && \
  npm install

ENTRYPOINT ["node", "/viewer/app.js"]
