name: Docker

on:
  schedule:
    - cron: "0 13 * * 1"
  workflow_dispatch:

jobs:
  docker:
    name: Build docker container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu-version:
          - 18.04
        node-version:
          - 14
        opencv-version:
          - 4.5.5
        runtime:
          - cpu
          - cuda
        openvslam-version:
          - 0.3.2
    steps:
      - uses: actions/checkout@v3
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu-version }}
            OPENCV_VERSION=${{ matrix.opencv-version }}
            NODEJS_MAJOR_VERSION=${{ matrix.node-version }}
            OPENVSLAM_VERSION=${{ matrix.openvslam-version }}
            NUM_THREADS=${{ steps.cpu-cores.outputs.count }}
          context: "./docker"
          file: "./docker/Dockerfile.${{ matrix.runtime }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openvslam-nodejs:ubuntu${{ matrix.ubuntu-version }}-openvslam${{ matrix.openvslam-version }}-node${{ matrix.node-version }}-opencv${{ matrix.opencv-version }}-${{ matrix.runtime }}